version: "3.9"

services:
  dumdumapi:
    build: .
    restart: always
    labels:
      - traefik.http.routers.api.rule=Host(`dumdum-api.mamun.cloud`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=lets-encrypt
      - traefik.port=8002
    networks:
      - internal
      - web
    ports:
      - "8002:8002"
networks:
  web:
    external: true
  internal:
    external: false

