version: "3.9"

services:
  dumdumapi:
    build: .
    restart: always
    labels:
      - traefik.frontend.rule=Host:dumdum-api.mamun.cloud
    networks:
      - internal
      - web
    ports:
      - "8002:8002"
networks:
  web:
    external: true
  internal:
    external: false

